services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://aiyzajunaid:7XnV9cfQTfNjGHNT@cluster0.epg20.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    command: npx nodemon server.js

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    stdin_open: true
    tty: true
